# Font configuration
[font]
size = 14.0 # Adjust to your liking

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular" 

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[colors.primary]
background = '#272e33'
foreground = '#d3c6aa'

[colors.normal]
black   = '#414b50'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
